### PR TITLE
Add new prebuilts

### PR DESCRIPTION
**Pull request by nicatronTg**
This adds new prebuilts for:

* SQLite
* MySQL
* Newtonsoft's JSON libraries

We build our own HttpServer (in this org) that should probably be updated, but I'm not that familiar with it (Steven Hartland did that).

BCrypt should still be up to date since I only added it fairly recently.

Also, all assemblies are for .NET 4.5. Also, it compiles on Mono.

This should satisfy #923, but I don't know if you want to recompile & pull changes for the HttpServer or not @MarioE?

### CODE REVIEW

**Comment by WhiteXZ** [comment]
Does this mean we now need to add .NET 4.5 as a requirement for running TShock (when 5.0 is released)?

**Comment by nicatronTg** [comment]
I was under the impression that it already was, so no?

**Comment by MarioE** [comment]
HttpServer doesn't really need to be updated.

**Comment by nicatronTg** [comment]
@MarioE if it looks good to you, feel free to merge.

**Pull request merged**
