### PR TITLE
Update all the GPL headers #1305

### LINKED ISSUE #1305: Update all the GPL headers
All of the GPL headers need to say the current year (2016) and files that don't have GPL headers need to have GPL headers.

### PR DESCRIPTION
**Pull request by adilsoncarvalho**
Update all years on the GPL headers to 2016 and add those headers when missing.

Resolves #1305

### CODE REVIEW

**Comment by nicatronTg** [comment]
@adilsoncarvalho just FYI you don't need to worry about adding the GPL header to anything other than code files c:

**Comment by nicatronTg** [comment]
Also just drop a note when you're done (you've labeled this as WIP so I assume it is) c:

**Comment by adilsoncarvalho** [comment]
I'm adding it only to all `.cs` files @nicatronTg

**Comment by adilsoncarvalho** [comment]
@nicatronTg there are lots of files without a header on a submodule. Should I add to them and commit? I saw no similar issue on its repository.

If not, the work here is done. I skipped also the generated files. No point in adding a header on them.

**Comment by nicatronTg** [comment]
@adilsoncarvalho no, but thank you for the offer! The submodule is proprietary code generated by a decompiler and monkey patched to work correctly. The license on code in that repository starts with "it's complicated," as we aren't really cross licensing it or anything.

Thanks!

**Comment by adilsoncarvalho** [comment]
LOL. This sould be a license! "It's complicated" 😛

**Comment by nicatronTg** [comment]
Definitely should :p

**Pull request merged**
