### PR TITLE
Add Hardened Stone to the list of tiles that can be altered by players.

### LINKED ISSUE #1138: Hardened Sand (Possible permission issue)
Corruption / Crimson / Hallowed counterpart of Hardened Sand isn't changing back to normal when contaminator / purification powder is used upon it. ( It will change back during world reset ) [ MIGHT only occur only in our server ].

However, when a "superadmin" used it it changed back, when a normal user used it, it would not change. As if the Hardened Sand block requires special permission. Be advised, other blocks around do change biomes by the users. Leading to believe it may be a permission issue, or another issue in tshock definition regarding a user changing block types.

image

### PR DESCRIPTION
**Pull request by DogooFalchion**
I added the hardened stone set of tiles to the list of exceptions in GetDataHandlers as well as refactored the existing ancient implementation into one that takes advantage of the TileID.Sets.Conversion sets for tile conversions.

This should fix #1138.

https://github.com/NyxStudios/TShock/pull/1313

### CODE REVIEW

**Comment by nicatronTg** [comment]
cc @NyxStudios/tshock

**Comment by WhiteXZ** [comment]
@DogooFalchion did you check that the sets used contain all the relevant IDs?

**Comment by DogooFalchion** [comment]
I did, thats why one of this looks murdered.

**Comment by Ijwu** [comment]
LGTM. Merging.

**Pull request merged**
