### PR TITLE
Add new code style guidelines

### PR DESCRIPTION
**Pull request by nicatronTg**
These are the code style guidelines from the consensus discussion from #908. Please sign off @Ijwu, @Enerdy, @WhiteXZ, @tylerjwatson, or suggest more changes.

Sign-off list:

- [x] @Enerdy 
- [x] @WhiteXZ 
- [ ] @Ijwu
- [ ] @tylerjwatson
- [x] @MarioE

### CODE REVIEW

**Comment by Enerdy** [comment]
I'm still not 100% confident with using `_field` for private fields instead of simply lower-casing them. I thought microsoft used `m_field`? Not that the latter is much better. We should simply use lower-case naming for private fields IMO.

With that being said I like the other changes, and I'm willing to sign this off even if we go with `_field`; I've used this in the past and it won't be hard for me to adapt.

**Comment by nicatronTg** [comment]
I really dislike the ```m_field``` convention @Enerdy, and I'll agree with you in that I think that private fields are fine lowercased. I'm going to try again and cc @NyxStudios/tshock and see if more people want to provide feedback on this.

**Comment by WhiteXZ** [comment]
``` m_field``` is horrible. 
I've been using ```_field``` in Orion

**Comment by nicatronTg** [comment]
I suppose the benefit to using ```_field``` is that it's a lot more noticeable that it's private than a lowercase versus uppercase letter.

**Comment by nicatronTg** [comment]
@MarioE got any feedback on this?

**Comment by MarioE** [comment]
Definitely use ```_field``` for privates. That's all my input on naming conventions. Will give style input shortly.

**Comment by nicatronTg** [comment]
Seems like consensus is ```_field``` which lines up with the rest of this change. I'm going to wait on @MarioE for additional feedback on the rest of the style changes.

**Comment by MarioE** [comment]
I will update this list as needed.

* Always use properties instead of public fields.
* When using static methods on primitives, use the CLR type. Use ```String.Format``` instead of ```string.Format```.
* Use ```[Obsolete(true)]``` to mark something as obsolete **and** give a compiler error when attempting to use the obsolete item.
* If a method or constructor can throw an exception, please document it with ```<exception cref="...Exception"/>```.

**Comment by nicatronTg** [comment]
@MarioE can you clarify something for me? Marking something ```[Obsolete("Please ...", true)]``` will still allow it to work in existing code, but will throw a compiler error for new code, correct?

**Comment by MarioE** [comment]
That's correct.

**Comment by nicatronTg** [comment]
Cool. I agree with those then.

**Comment by nicatronTg** [comment]
@MarioE I've pushed the latest version; are you on board? I'm okay with this version, but I've unchecked @WhiteXZ and @tylerjwatson for the time being to see if they're still okay with this.

**Comment by Enerdy** [comment]
Cool. I'm fine with those now.

**Comment by nicatronTg** [comment]
@MarioE @Enerdy @WhiteXZ feel free to merge whenever.

**Pull request merged**
