### PR TITLE
A possible fix for #1337

### PR DESCRIPTION
**Pull request by ProfessorXZ**

### CODE REVIEW

**Comment by ProfessorXZ** [comment]
I approve of this.

**Comment by DogooFalchion** [comment]
Why is this a _possible_ fix and not an _actual_ fix?

**Comment by ProfessorXZ** [comment]
Because noone answered 2 questions I asked and I have no idea how to reproduce this.

**Comment by Enerdy** [comment]
I approve of this possible fix, but because it is not a certain fix there is no guarantee this will actually fix anything.

**Comment by ProfessorXZ** [comment]
Back on topic, I'm 99% sure this is what was causing issues.

**Comment by ProfessorXZ** [comment]
1. I don't know what you want me to say here, it fixes #1337. Inventories were messed up because invalid slot indexes have been passed to the server. The server read the database info correctly but the client was sending invalid values.

2. Superbowser has confirmed this fix works. 
```
professorx [8:52 AM]  
@superbowser does SSC work properly or not

newy [8:53 AM]  
Any super geniuses wanna help a noob in #plugins

superbowser [1:39 PM]  
@professorx Works properly, even the Forge works.

professorx [3:19 PM]  
Thanks```

3. Changelog updated.

**Pull request merged**
