### PR TITLE
Possibly fixes #922

### LINKED ISSUE #922: Remove old REST permission model
"When the next maintenance release of TShock happens" has been several releases ago.

### PR DESCRIPTION
**Pull request by Strinkor**

### CODE REVIEW

**Comment by Enerdy** [comment]
I suggest we delay this until we launch the new V4 endpoints.

**Comment by Strinkor** [comment]
@Enerdy, maybe, i can help with V4? If yes, how i can help? :)

**Comment by Enerdy** [comment]
See #867.

**Comment by Strinkor** [comment]
@Enerdy, can you assign it to me?

**Comment by Ijwu** [comment]
No. This is something that is coming in Orion/TShock 5.0. It is not currently a priority. As such, this PR should be denied for right now. 

Thanks for contributing @Strinkor! It's just not the time for this, we'll revisit this when we're on stable ground and we're going back to active TShock 5.0 development.

**Pull request closed without merging**
