### PR TITLE
Fixed UI issues caused by setting wind speed to high values

### PR DESCRIPTION
**Pull request by ProfessorXZ**

### CODE REVIEW

**Comment by WhiteXZ** [comment]
:+1:

**Comment by Enerdy** [comment]
The thing I don't get about this PR is: even if Terraria multiplies speed by 100 to perform calculations, why would you have to do the same if the only purpose of your check is to find out if `speed` is negative? A negative number will still be negative after being multiplied by 100.

**Comment by WhiteXZ** [comment]
The issue is with integer overflows, @Enerdy: excessively high speeds will be multiplied by 100 and overflow, resulting in -Int32.MaxValue speeds

**Comment by Enerdy** [comment]
Interesting. I thought that would throw some kind of exception, but apparently it simply turns into negative.

**Pull request merged**
