### PR TITLE
Specify which item is causing a player to be disabled. Fixes #909.

### LINKED ISSUE #909: Log more info on automatic player disabling by cheat checks
Right now, whenever a player gets disabled by one of tshock's cheating checks, such as for using a banned item or wearing a banned armor, the console/log will only inform the host that the player got disabled, but will fail to give them any information regarding which item caused the check to trigger. We should at least add the item id to the informational message, be it on log-only, console, or both.

### PR DESCRIPTION
**Pull request by Enerdy**
Also fixed some random indentation along the way...

### CODE REVIEW

**Comment by nicatronTg** [comment]
**Please stop pushing code to your fork. Please branch in this repository and follow Github flow so that other contributors can add to your work in the future**.

**Comment by nicatronTg** [comment]
Fix those issues and we'll be good @Enerdy.

**Comment by KamranMackey** [comment]
> **Please stop pushing code to your fork. Please branch in this repository and follow Github flow so that other contributors can add to your work in the future.**

Uh, how is he supposed to contribute unless he pushes to his fork?

**Comment by nicatronTg** [comment]
@KamranMackey via [Github Flow?](https://guides.github.com/introduction/flow/)

**Comment by Enerdy** [comment]
Addressed. Ready to deploy. Waiting for merge procedure.

**Comment by nicatronTg** [comment]
lgtm

**Pull request merged**
