### PR TITLE
User Permissions

### PR DESCRIPTION
**Pull request by Enerdy**
This PR is not yet finished, but I'm pushing it at @nicatronTg's request. My next todo is to address User IDs, as every user should have an ID at all times. Discuss.

### CODE REVIEW

**Comment by Enerdy** [comment]
Would it be wise to close this PR and commit to new-permissions so that others can contribute, too? Just applying the concepts of Github Flow, which seems to be what we'll be using from now on.

**Comment by nicatronTg** [comment]
That's kinda up to you, but for the record, it doesn't currently build.
Because it's a pull request from one branch to another non general-devel
branch, I don't see a reason why not.

**Comment by Enerdy** [comment]
Now that the build has been unbroken, I've merged this Pull Request into NyxStudios:new-permissions so that we may follow github flow guidelines. NyxStudios:new-permissions will eventually be merged with general-devel once it is ready for deployment.

**Comment by nicatronTg** [comment]
Thanks @Enerdy!

**Pull request merged**
