### PR TITLE
Do not merge: Move to Mintaka.

### PR DESCRIPTION
**Pull request by nicatronTg**
This is the general pull request for discussing merging into Mintaka. Because of the unique nature of this project, we're soliciting feedback and changes more openly than ever.

Todo:

- [x] Build on Linux
- [x] Build on Travis / update build scripts
- [ ] Sort out all the bugs
- [x] Update changelog

### CODE REVIEW

**Comment by nicatronTg** [comment]
_General code review also requested_

**Comment by nicatronTg** [comment]
@NyxStudios/tshock I'm good with this merging but before it merges, someone needs to double code review check it. On the API side, I think we need to have at least one version tick and then merge the mintaka branch into general-devel. Then we update the submodule here, update the changelog, and merge.

**Comment by Enerdy** [comment]
It should be added that this should be a major version tick (as suggested by White) because plugins are unable to function without being recompiled unlike previous releases.

**Comment by nicatronTg** [comment]
@Enerdy 👍 

https://github.com/NyxStudios/TerrariaAPI-Server/commit/9e87b3a33f0cb97b4e0a72e2694c3f69bb55b63e

**Pull request merged**
