### PR TITLE
DEBUG preprocessor checks for ILog

### PR DESCRIPTION
**Pull request by WhiteXZ**
Because TraceLevel does not have a Debug value

### CODE REVIEW

**Comment by Olink** [comment]
I dont quite understand this commit, why didnt you just put the preprocessor conditional inside Debug() so it changed one file in one line.

**Comment by nicatronTg** [comment]
Yeah, that.

**Comment by WhiteXZ** [comment]
This way TShock.Log.Debug doesn't exist unless you're using a debug build, so people won't attempt to use it

**Comment by Olink** [comment]
But people will want to use it?  They just want the function to NOP if debug isnt specified.

**Comment by WhiteXZ** [comment]
Why would they want to use a function that does nothing when DEBUG is not specified?

**Comment by Olink** [comment]
Because we build in release, so they can never physically compile against a build with the debug log statement, which means even if they build for debug they cant use it.  You might as well as delete the entire function and its uses at that point.

**Comment by nicatronTg** [comment]
Because it allows them to not change their codebase for debug...

You :ninja: Zack. That.

**Comment by Olink** [comment]
I would be inclined to agree that in a Release build we don't even need to compile code for debugging, however, since we provide release binaries to the server owners, there is no way for a developer to run a debug build on an actual production environment to understand why something doesnt work, and traditionally, you don't remove functions entirely from a build (unless they serve 0 purpose and are only for your development of your software for your testing), you NOP them.

**Comment by Olink** [comment]
While not related to this PR, can we take a moment to discuss how bad we are at removing deprecation :kappa:

The entire Log.cs file needs to be removed, as its a shim to TShock's Log member.

**Comment by nicatronTg** [comment]
Looks much better @WhiteXZ.

**Pull request merged**
