### PR TITLE
Adds a time parameter to the tempgroup command

### PR DESCRIPTION
**Pull request by WhiteXZ**
Adds #893

### CODE REVIEW

**Comment by nicatronTg** [comment]
:+1: This is LD. We are go for launch.

@Olink MD, please verify GO for launch.

**Comment by Olink** [comment]
Wait for travis, the first pr did something weird to some region code using timers or something, this one does not, ensure that it builds and we are go for launch.

**Comment by nicatronTg** [comment]
@Olink avi is go, MD, please verify go for launch.

**Comment by Olink** [comment]
This is md, I just got word from the travis department that they could in fact verify the integrity of the shuttle, we are a go for launch.  I repeat we are a go for launch, please launch when ready.

**Comment by nicatronTg** [comment]
Entering terminal count, please stand by for final launch sequence.

**Pull request merged**
