### PR TITLE
Refactor some of the mess that is NetItem and PlayerData.

### LINKED ISSUE #1340: Couldn't join game in TShock Mintaka Unstable build 1386
Terraria would always be "Requesting world information".

But if you revert [this commit 1741b0c](https://github.com/NyxStudios/TShock/commit/1741b0c854311a23814731b5acfed6b72e9c75a2), players will be able to join the server again.

### PR DESCRIPTION
**Pull request by DogooFalchion**
NetItem and PlayerData are more sane.  

Can not reproduce the SSC corruption with this.

Steps taken:
1) Enable SSC
2) Register Character
3) Log in to character
4) Give items and fill random slots of inventory.
5) Fill random slots of piggy/safe/forge.
6) Log out
7) Log in
8) Check inventories.

Everything was as expected.

This probably fixes #1340 and #1337, as neither occur with this build.

### CODE REVIEW

**Comment by nicatronTg** [comment]
I only tested joining, but this server worked for me. This may be a fix for #1340 too.

**Comment by nicatronTg** [comment]
According to @Enerdy he didn't test this, so still need 2 more reviews or testers.

**Comment by nicatronTg** [comment]
screen shot 2016-12-12 at 4 07 57 pm

**Comment by Enerdy** [comment]
I have followed the same steps as the OP and was unable to reproduce the SSC corruption issue.
imagem

**Comment by nicatronTg** [comment]
Did everything outlined here, didn't seem to have any corrupted inventories.

**Comment by nicatronTg** [comment]
DO NOT MERGE. 🙅🙅🙅🙅

DID NOT UPDATE CHANGELOG.

**Pull request merged**
