### PR TITLE
Issue #1371: Grant logout permissions by default

### PR DESCRIPTION
**Pull request by aarongoulet**

### CODE REVIEW

**Comment by DogooFalchion** [comment]
I suppose this works because default inherits from guest, but since a guest by definition is someone who isnt logged in I am opposed to it being a part of the guest group which by definition is someone who is not logged in (a guest can run logout which seems silly since they arent logged in :) ).

**Comment by aarongoulet** [comment]
@DogooFalchion That makes sense; I probably should have looked a little more closely at the definitions before submitting my request. ;) I'll make the necessary corrections shortly!

**Comment by aarongoulet** [comment]
@DogooFalchion After going back and looking at the source code, I remember the reasoning behind that design decision: the logout command has a built-in handler that helpfully tells you, "You are not logged in," when attempting to log out as guest, which, to a general user, is more helpful (less ambiguous) than an insufficient permissions message.  That being said, it IS a design decision, and I'll defer to your judgement; let me know if you'd still like it moved to the 'default' category.

**Comment by WhiteXZ** [comment]
I have to agree that logout should probably not be in guest by default.
The user-friendly message is good to have, but not providing guests access to logout is a better design.
Depending on how hacky things would have to get, maybe a work-around could be found to keep the 'You are not logged in' message

**Comment by aarongoulet** [comment]
@WhiteXZ From what I can tell it might need to get pretty hacky to change the message due to the fact that permissions are abstracted from the the actual command execution code.  That being said, I'll be happy to update my pull request and move the logout command from the 'guest' group as soon as I get a chance today (I've got to head to work in a few).  Thank you for the feedback!

**Comment by hakusaro** [comment]
Can't tell if trolling

**Comment by aarongoulet** [comment]
Not trolling, just a mistake on my part. I was trying to get a clean, fresh fork without losing this specific pull request, since my changes are so minor. I'm not 100% sure the best way to do this with GitLab.

**Comment by aarongoulet** [comment]
By the way, changes made. Atom removed some trailing whitespace on some other lines, which was another reason I was trying for a clean branch.  Sorry for the confusion!

**Comment by hakusaro** [comment]
Umm, yeah. You don't want to delete the branch associated with a PR. You can update by:

```
git remote add upstream git@github.com:NyxStudios/TShock.git
git fetch upstream
...[git will fetch the upstream remote and create new branches locally to match]...
git merge [whatever git created as the general-devel branch from upstream]
git push origin general-devel
[or to update this pr substitute the last command with:]
git push origin logout-permissions-change
```

**Comment by aarongoulet** [comment]
Thanks! This is actually kinda embarrassing; I work with Git on a daily basis at work but we don't use a lot of the features that make it such an amazing tool.  I appreciate you taking the time to help a new contributor, @hakusaro!

**Comment by hakusaro** [comment]
> I work with Git on a daily basis at work

Hilariously, this has been my usual experience. I know how to do some but not all features. Rebasing is still a nightmare to me and I can never get it to start and run correctly. Once I learned about ```git reflog``` my life became a lot better but I still only know tangentially when to use it. Cheers c:

**Comment by aarongoulet** [comment]
Thanks. :) So, from what I am seeing it looks like the GitHub desktop client already updated my branch from the master  I reviewed my commits/files changed and it looks about right. Not sure why automatic merging is blocked though.

**Comment by aarongoulet** [comment]
Verification:
https://github.com/aarongoulet/TShock/commits/logout-permissions-change

**Comment by hakusaro** [comment]
> Not sure why automatic merging is blocked though.

Pending code review.

screen shot 2017-04-13 at 10 15 43 pm

**Pull request merged**
